// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCD3G-FtSNe-zWDqxIltC8UxrpT9rUIHM',
    appId: '1:425619219360:web:64c6f0a3d57ecf6ff3bac5',
    messagingSenderId: '425619219360',
    projectId: 'lms-project-a9747',
    authDomain: 'lms-project-a9747.firebaseapp.com',
    storageBucket: 'lms-project-a9747.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHS-AuGE650a5T4bUoOZXtrcwgDbPQdBA',
    appId: '1:425619219360:android:6438a08b8292a88ef3bac5',
    messagingSenderId: '425619219360',
    projectId: 'lms-project-a9747',
    storageBucket: 'lms-project-a9747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBw6BZtAUenkEBb8-w-GBgBBR47jA8IZEQ',
    appId: '1:425619219360:ios:21789b4d0ae26002f3bac5',
    messagingSenderId: '425619219360',
    projectId: 'lms-project-a9747',
    storageBucket: 'lms-project-a9747.firebasestorage.app',
    iosBundleId: 'com.example.aiLmsProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBw6BZtAUenkEBb8-w-GBgBBR47jA8IZEQ',
    appId: '1:425619219360:ios:21789b4d0ae26002f3bac5',
    messagingSenderId: '425619219360',
    projectId: 'lms-project-a9747',
    storageBucket: 'lms-project-a9747.firebasestorage.app',
    iosBundleId: 'com.example.aiLmsProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCD3G-FtSNe-zWDqxIltC8UxrpT9rUIHM',
    appId: '1:425619219360:web:4f86900f1ed1e280f3bac5',
    messagingSenderId: '425619219360',
    projectId: 'lms-project-a9747',
    authDomain: 'lms-project-a9747.firebaseapp.com',
    storageBucket: 'lms-project-a9747.firebasestorage.app',
  );
}
